# ==============================================================================
# Inventory   : inventory.ini
# Description : Sample Ansible inventory for homelab infrastructure deployment
# Author      : SudoShea
# Version     : 1.9.0
# Licence     : MIT
# ==============================================================================
[primary_servers]
pihole-primary ansible_host=<primary_ip> ansible_user=<username> ansible_python_interpreter=/usr/bin/python3

[secondary_servers]
pihole-secondary ansible_host=<secondary_ip> ansible_user=<username> ansible_python_interpreter=/usr/bin/python3

[dns_servers:children]
primary_servers
secondary_servers

[storage_servers:children]
secondary_servers

[homelab_nodes:children]
dns_servers
storage_servers

[homelab_nodes:vars]
secondary_storage_host=<secondary_ip>
secondary_storage_user=<username>
