# ==============================================================================
# Inventory   : inventory.ini
# Description : Sample Ansible inventory for homelab infrastructure deployment
# Author      : SudoShea
# Version     : 1.0.1
# License     : MIT
# ==============================================================================
[homelab]
localhost ansible_connection=local

# Example Remote Host (Raspberry Pi):
# 192.168.1.50 ansible_user=shea ansible_ssh_private_key_file=~/.ssh/id_ed25519
