# ==============================================================================
# Inventory   : inventory.ini
# Description : Sample Ansible inventory for homelab infrastructure deployment
# Author      : SudoShea
# Version     : 1.4.0
# License     : MIT
# ==============================================================================
[homelab]
pihole ansible_host=<PiHole IP> ansible_user=<user> ansible_python_interpreter=/usr/bin/python3

[home_server]
HOME-SERVER ansible_host=<Server IP> ansible_user=<user> ansible_python_interpreter=/usr/bin/python3
