# ==============================================================================
# Requirements : requirements.yml
# Description  : External role and collection dependencies for homelab stack
# Author       : SudoShea
# Version      : 1.8.4
# Licence      : MIT
# ==============================================================================
---
roles:
  - name: linux_backup_automation
    src: git+https://github.com/SudoShea/linux-backup-automation.git
    version: v1.1.0

collections:
  - name: containers.podman
  - name: community.general
