# ==============================================================================
# Playbook    : site.yml
# Description : Master Ansible playbook for homelab infrastructure deployment
# Author      : SudoShea
# Version     : 1.8.3
# License     : MIT
# ==============================================================================
---
- name: Deploy Rootless Podman Homelab Stack
  hosts: homelab_nodes
  gather_facts: true
  roles:
    - podman_stack

- name: Deploy Encrypted Backup Engine (Primary Source Host Only)
  hosts: primary_servers
  gather_facts: true
  roles:
    - role: linux_backup_automation
      become: true

- name: Deploy Centralized Logging Server (Loki & Grafana)
  hosts: storage_servers
  gather_facts: true
  roles:
    - logging_server

- name: Deploy Log Shipper (Vector)
  hosts: homelab_nodes
  gather_facts: true
  roles:
    - logging_shipper
