# ==============================================================================
# Workflow    : .github/workflows/lint.yml
# Description : GitHub Actions CI workflow for Ansible-Lint static analysis
# Author      : SudoShea
# Version     : 1.8.4
# Licence     : MIT
# ==============================================================================
name: Ansible Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  ansible-lint:
    name: Ansible-Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Create dummy vault password file for CI
        run: echo "dummy_ci_vault_password" > .vault_pass

      - name: Run Ansible-Lint
        uses: ansible/ansible-lint@main
